### ISSUE TITLE
Can't slew to manual Alt/Az target after update to v3.2

### ISSUE THREAD

**Issue by RichardCullip** [isbeorn/nina#154]
I just upgraded to NINA 3.2 and have run into a minor frustration. In 3.1 I was able to use the Mount page to do a manual slew to a specified Alt/Azim. Now, when I try this, NINA 3.2 does not move the mount but just goes into an immediate scope settling count down. I have updated the AM5N firmware, installed the latest ASCOM drivers from ZWO and synced the mount to NINA all to no avail. Not sure what to do next to be able to use the manual slew command in NINA. I can slew to a target in the framing wizard and inside PHD2 so it obvious that NINA is talking to my mount just not with the manual slew command on the Mount page.

**To Reproduce**
1. Go to Equipment->Mount page
2. Enter Alt/AZ manual target values
3. Click on  Slew

**Expected behavior**
I expect the mount to slew to the target but the mount doesn't move

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 24h2
 - Version 26100.7462

**Additional context**
Manual slew to Alt/Az target worked fine on NINA v3.

[20260111-140000-3.2.0.9001.4888-202601.log](https://github.com/user-attachments/files/24555332/20260111-140000-3.2.0.9001.4888-202601.log)

1HF2.
I can Manual Slew to RA/Dec target but not an Alt/Az target

**Comment by daleghent** [comment]
The root issue is that the ZWO's ASCOM driver for their mounts does not implement the required API that allows an ASCOM client  to  directly command a slew by altitude and azimuth degrees. It implements only the API for slewing by right ascension and declination coordinates. The vast majority of mount drivers normally implement the alt+az slewing API, so the absence of it in ZWO's own driver is rather unique.

In 3.2, NINA moved to using the alt+az slewing API directly whereas before it would slew to alt+az coordinates by first converting them to RA+dec equivalents then commanding the mount slew to that RA+dec. This had some unintended effects with some mount drivers, however, due to some differing ASCOM semantics between slewing by RA+dec and slewing by alt+az. NINA was changed to using the direct alt+az slew API instead of doing the conversion to RA+dec. Because the ZWO driver does not implement the alt+az slew API, slews by alt+az no longer happen on ZWO mounts.

In 3.3, the original conversion to RA+dec is put in place for mount drivers that do not support directly slewing by alt+az. 

The better fix is for ZWO to implement slewing by alt+az in their mount driver, as the vast majority of mount drivers already do (and why, so far, this issue has been noticed only on the ZWO mounts)

**Comment by RichardCullip** [comment]
Thanks for the detailed explanation Richard Cullip On Jan 11, 2026, at 2:59 PM, Dale Ghent ***@***.***> wrote:﻿daleghent left a comment (isbeorn/nina#154)
The root issue is that the ZWO's ASCOM driver for their mounts does not implement the required API that allows an ASCOM client  to  directly command a slew by altitude and azimuth degrees. It implements only the API for slewing by right ascension and declination coordinates. The vast majority of mount drivers normally implement the alt+az slewing API, so the absence of it in ZWO's own driver is rather unique.
In 3.2, NINA moved to using the alt+az slewing API directly whereas before it would slew to alt+az coordinates by first converting them to RA+dec equivalents then commanding the mount slew to that RA+dec. This had some unintended effects with some mount drivers, however, due to some differing ASCOM semantics between slewing by RA+dec and slewing by alt+az. NINA was changed to using the direct alt+az slew API instead of doing the conversion to RA+dec. Because the ZWO driver does not implement the alt+az slew API, slews by alt+az no longer happen on ZWO mounts.
In 3.3, the original conversion to RA+dec is put in place for mount drivers that do not support directly slewing by alt+az.
The better fix is for ZWO to implement slewing by alt+az in their mount driver, as the vast majority of mount drivers already do (and why, so far, this issue has been noticed only on the ZWO mounts)

**Comment by isbeorn** [comment]
This will be fixed by https://github.com/isbeorn/nina/commit/75c85 in 3.3
